Unittest
zaqbez39me/Random-Generator pull request #7
Opened 2024-04-23 20:31 UTC by starkda

2024-04-25 11:30 UTC, zaqbez39me requested changes

2024-04-25 11:30 UTC, zaqbez39me commented on docker-compose.yml
> +      - "random_generator/tests/.env"
Seems strange to use .env from tests folder everywhere

2024-04-25 11:30 UTC, zaqbez39me commented on deploy/docker-compose.yml
> +    - ../random_generator/tests/.env
Also seems strange to use .env from tests folder everywhere

2024-04-25 11:30 UTC, zaqbez39me commented on .gitignore
We still should ignore .env file

2024-04-25 11:30 UTC, zaqbez39me commented on .env
Bad idea to include `.env` file in repo

2024-04-25 11:30 UTC, zaqbez39me commented on .dockerignore
We still need to ignore `.env` file

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/.env
It should be ignored

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/settings.py
> +    news_api_key: str = "d66cfea1da25452cbeed425c9fa16dc9"
Bad idea to include real API key as default value

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/tests/integration_tests/.env
It should be ignored. Consider using `.env.example` naming if it is used as example.

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/tests/test_news_seed_fetcher.py
> +    data = NewsSeedFetcher._NewsSeedFetcher__fetch_data()  # type: ignore[attr-defined]
Seems to be not the best idea to use protected attrs. Maybe, you could avoid it

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/tests/test_news_seed_fetcher.py
> +    seed = NewsSeedFetcher._NewsSeedFetcher__encode_data(  # type: ignore[attr-defined]
Seems to be not the best idea to use protected attrs. Maybe, you could avoid it

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/tests/test_news_seed_fetcher.py
> +    "random_generator.web.api.random.seed_fetchers.NewsSeedFetcher._NewsSeedFetcher"
Protected access

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/tests/test_news_seed_fetcher.py
> +    "random_generator.web.api.random.seed_fetchers.NewsSeedFetcher._NewsSeedFetcher"
Protected access

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/tests/test_time_seed_fetcher.py
> +    data = TimeSeedFetcher._TimeSeedFetcher__fetch_data()  # type: ignore[attr-defined]
Protected access

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/tests/test_time_seed_fetcher.py
> +    seed = TimeSeedFetcher._TimeSeedFetcher__encode_data(time_data)  # type: ignore[attr-defined]
Protected access

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/tests/test_weather_seed_fetcher.py
> +    data = WeatherSeedFetcher._WeatherSeedFetcher__fetch_data()  # type: ignore[attr-defined]
Protected access

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/tests/test_weather_seed_fetcher.py
> +    seed = WeatherSeedFetcher._WeatherSeedFetcher__encode_data(weather_data)  # type: ignore[attr-defined]
Protected access

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/web/api/random/seed_fetchers.py
> +import requests  # type: ignore[import-untyped]
This ignore seems to be strange. What is the cause?

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/web/api/random/seed_fetchers.py
> +        ok = 200
Not the best practise to use the extra variables where it is unneded

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/web/api/random/seed_fetchers.py
> +        base = 32
Also the variables seems not to be very needed here

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/web/api/random/seed_fetchers.py
> +        ok = 200
This varaible seem to be redundant

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/web/api/random/seed_fetchers.py
> +        base = 16
Theese two variables seem to be redundant

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator/web/api/random/seed_fetchers.py
> +        ok = 200
This variables seem to be redundant

2024-04-25 11:30 UTC, zaqbez39me commented on random_generator_front_end/streamlit_app.py
> +    ok = 200
This variables seem to be redundant

2024-04-26 12:29 UTC, starkda commented
@zaqbez39me 
ну, у нас такой чекстайл. flake8 не дает использовать magic numbers.
Насчет .env - снизят ли нам балы на них? Думаю, нет. Так что не вижу смысла тратить время на этот фикс

2024-04-26 15:51 UTC, zaqbez39me approved these changes

2024-04-26 15:51 UTC, merged